---

version: '3.8'

services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"   # для Celery
      - "15672:15672" # для веб-интерфейса RabbitMQ

  sftp:
    image: atmoz/sftp
    volumes:
      - /home/user/upload:/home/foo/upload
    ports:
      - "2222:22"
    command: foo:pass:1001

  api:
    build: .
    command: uvicorn webapp.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./webapp:/opt/webapp
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy

  worker:
    build: .
    command: watchmedo auto-restart --directory=/opt/webapp --pattern=*.py --recursive -- celery -A webapp.celery_worker.celery_app worker --loglevel=info
    volumes:
      - ./webapp:/opt/webapp
    env_file:
      - ./.env
    depends_on:
      - rabbitmq
      - api

  beat:
    build: .
    command: watchmedo auto-restart --directory=/opt/webapp --pattern=*.py --recursive -- celery -A webapp.celery_worker.celery_app beat --loglevel=info
    volumes:
      - ./webapp:/opt/webapp
    env_file:
      - ./.env
    depends_on:
      - rabbitmq
      - api

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio_server
    # Порты: 9000 для API/S3, 9001 для консоли (UI)
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    volumes:
      - minio_data:/data
    command: minio server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 10s


volumes:
  postgres_data:
  minio_data:

